### ISSUE TITLE
option to remove new lines during compression

### ISSUE THREAD

**Issue by prabirshrestha** [stevelacy/gulp-stylus#10]
would love to have option to remove white lines during compression.

currently here is the output when minified.

``` css
.clear{clear:both}
.hidden{display:none}
```

would love to see it as.

``` css
.clear{clear:both};.hidden{display:none}
```
