### ISSUE TITLE
Who write vendor prefixes? Don't use nib

### ISSUE THREAD

**Issue by h0tc0d3** [stevelacy/gulp-stylus#192]
Input:
```css
@keyframes rotateCircle
  0% blbla
```
Output:
```css
@-moz-keyframes rotateCircle {
  0% {
    transform: rotate(0deg);
  }
}
@-webkit-keyframes rotateCircle {
  0% {
    transform: rotate(0deg);
  }
}
@-o-keyframes rotateCircle {
  0% {
    transform: rotate(0deg);
  }
}
@keyframes rotateCircle {
  0% {
    transform: rotate(0deg);
  }
}
```
```javascript
gulp.task("css", function () {
    return gulp.src("./src/css/style.styl")
        .pipe(sourcemaps.init())
        .pipe(stylus())
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("./static"));
});
```
Who add prefixes? I do not need extra prefixes, for this purpose I use autoprefixer.
