### ISSUE TITLE
`resolve url` option doesn't work

### ISSUE THREAD

**Issue by th0r** [stevelacy/gulp-stylus#20]
I use `gulp-stylus` like this:

``` js
gulp.task('styles.app', function () {
    return gulp
        .src('app/styles/styles.styl')
        .pipe(stylus({
            set: ['resolve url']
        }))
        .pipe(gulp.dest('public/app/styles'));
});
```

`app/styles/styles.styl` content:

``` css
@import 'includes/header'
```

`app/styles/includes/header.styl` content:

``` css
.logo {
    background url("../img/logo.png")
}
```

When I compile `styles.styl` using CLI like this:

``` bash
stylus --resolve-url app/styles/styles.styl -o public/app/styles
```

... it compiles to:

``` css
.logo {
  background: url("img/logo.png");
}
```

But if I use `gulp styles.app`, then it compiles to:

``` css
.logo {
  background: url("../img/logo.png");
}
```
