### ISSUE TITLE
nib issue

### ISSUE THREAD

**Issue by arb** [stevelacy/gulp-stylus#45]
The plugin doesn't appear to be using the `nib` module even when it's passed in per the documentation.

This is a striped down CSS file to show the example

``` css
.label {
  linear-gradient(top, white, green);
  display: flex;
}
```

After running the gulp task results in 

``` css
.label {
  display: flex;
}
```

It's like the task isn't using `nib` at all. My gulp task looks like this

``` javascript
gulp.task('test', function () {
  return gulp.src('assets/css/test.styl')
    .pipe(stylus({
      use: [nib()]
    }))
    .pipe(gulp.dest('public/css'))
    .pipe(notify({ message: 'CSS task complete' }));
})
```

Essentially a copy and paste from the examples. 

Am I doing something wrong? Is there a version mismatch somewhere perhaps?
