### ISSUE TITLE
@import-ing a stylus file with a loop in it results in only outputing contents of said loop

### ISSUE THREAD

**Issue by izeau** [stevelacy/gulp-stylus#68]
I have found this really weird bug…
- gulp: 3.8.6
- gulp-stylus: 1.1.0

---
###### Source files

``` stylus
// test1.styl
a
  color red

for i in (1..3)
  b
    color green

c
  color blue
```

``` stylus
// test2.styl
@import "test1"
```

``` javascript
// gulpfile.js
var gulp   = require("gulp");
var stylus = require("gulp-stylus");

gulp.task("styles", function() {
  return gulp.src("*.styl")
    .pipe(stylus())
    .pipe(gulp.dest("."));
});
```

---
###### Result

``` css
/* test1.css */
a {
  color: #f00;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
c {
  color: #00f;
}
```

``` css
/* test2.css */
b {
  color: #008000;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
```

---
###### Expected result (from command-line stylus)

``` css
/* test2.css */
a {
  color: #f00;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
c {
  color: #00f;
}
```

---

Sidenote: I find interesting the fact that CSS-`green` is the only one of the famous `red, green, blue` trio not to have a 255-value composant. `red` is `#f00`, `blue` is `#00f`, but `green` is `#008000`. I wonder what went through their heads… :no_mouth:
